appserver:
  name: appserver
  replicas: 3

  image:
    name: appserver
    tag: v2 
    port: 3000

  env:
    NODE_ENV: production
  
  service:
    name: appserver-clusterip-service
    type: ClusterIP


nginx:
  name: nginx
  replicas: 1

  image:
    name: nickyasaph/app-nginx
    tag: v3
    port: 80

  service:
    name: app-nginx-loadbalancer-service
    type: LoadBalancer


userservice:
  name: userservice
  replicas: 2

  image:
    name: userservice
    tag: v1
    port: 4000
  
  service:
    name: userservice-clusterip-service
    type: ClusterIP

