apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userservice.service.name }}
spec:
  type: {{ .Values.userservice.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.userservice.image.port }}
  selector:
    server: {{ .Values.userservice.name }}