apiVersion: apps/v1
kind: Deployment

metadata:
  name: userservice-deployment
spec:
  replicas: 2

  selector:
    matchLabels:
      server: userservice
  template:
    metadata:
      labels:
        server: userservice
    spec:
      containers:
        - name: userservice
          image: userservice:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
